attend/urls.py
from django.urls import path
from . import views # ←これ忘れないようにする！！

app_name = 'attend'
urlpatterns = [
    path('', views.index, name='index'),
    path('result/', views.result, name='result'),
    path('err_cause/', views.Err, name="err_cause"),
    path('result_err/', views.result_err, name="result_err"),
    path('result_err/', views.forget, name="forget"),
    path('result_forget/', views.result_forget, name="result_forget")
]

kintai/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_title = '勤怠管理システム（管理者サイト）' 
admin.site.site_header = '管理者サイト' 
admin.site.index_title = '勤怠管理システム（管理者サイト）'

urlpatterns = [
    path('', include('attend.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

attend/models.py
from django.db import models
from django.contrib.auth import get_user_model

#勤怠管理model
class SubmitAttendance(models.Model):

    class Meta:
        db_table = 'attend'
        verbose_name = '勤怠管理'
        verbose_name_plural = '勤怠管理'
    
    
    IN_OUT = (
        (1, '出勤'),
        (0, '退勤'),
    )
    staff = models.ForeignKey(get_user_model(), verbose_name="スタッフ", on_delete=models.CASCADE, default=None)
    in_out = models.IntegerField(verbose_name='出勤/退勤', choices=IN_OUT, default=None)
    time = models.TimeField(verbose_name="打刻時間")
    date = models.DateField(verbose_name='打刻日')

#打刻エラーmodel
class SubmitError(models.Model):
    class Meta:
        db_table = 'submit_err'
        verbose_name = 'エラー'
        verbose_name_plural = 'エラー'
    ERR_CAUSE = (
        (1, '打刻忘れ'),
        (2, '打刻ミス')
    )
    staff = models.ForeignKey(get_user_model(), verbose_name="スタッフ", on_delete=models.CASCADE, default=None)
    err_cause = models.IntegerField(verbose_name='ERR_CAUSE', choices=ERR_CAUSE, default=None)

#働き過ぎを記録するmodel
class OverWorkTime(models.Model):
    class Meta:
        db_table = 'OverWork'
        verbose_name = '働きすぎリスト'
        verbose_name_plural = '働きすぎリスト'
    staff = models.ForeignKey(get_user_model(), verbose_name="スタッフ", on_delete=models.CASCADE, default=None)
    date_time_in = models.DateTimeField(verbose_name="出勤時間")
    date_time_out = models.DateTimeField(verbose_name="退勤時間")
    worktime = models.CharField(verbose_name="労働時間", max_length=5)

#打刻忘れを記録するmodel
class SubmitForget(models.Model):
    class Meta:
        db_table = 'DakokuForget'
        verbose_name = '打刻忘れリスト'
        verbose_name_plural = '打刻忘れリスト'
    IN_OUT = (
        (1, '出勤'),
        (0, '退勤'),
    )
    staff = models.ForeignKey(get_user_model(), verbose_name="スタッフ", on_delete=models.CASCADE, default=None)
    in_out = models.IntegerField(verbose_name='出勤/退勤', choices=IN_OUT, default=None)
    date_time_forget = models.DateTimeField(verbose_name="忘れた打刻時間")

attend/forms.py
from django import forms
from .models import SubmitAttendance, SubmitError, SubmitForget

class SubmitAttendanceForm(forms.ModelForm):

    class Meta:
        model = SubmitAttendance
        widgets = {
            'in_out': forms.RadioSelect()
        }
        fields = ('in_out',)

class SubmitErrForm(forms.ModelForm):

    class Meta:
        model = SubmitError
        widgets = {
            'err_cause': forms.RadioSelect()
        }
        fields = ('err_cause', )


class SubmitForgetForm(forms.ModelForm):
    date_time_forget = forms.DateTimeField(
        input_formats = ['%Y-%m-%d %H:%M:%S'],
        widget=forms.DateTimeInput(attrs={
            'type': 'datetime-local',
            'class': 'form-control'
        })
    )
    class Meta:
        model = SubmitForget
        fields = ('date_time_forget',)
    

attend/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import SubmitAttendance, SubmitError, OverWorkTime
from .forms import SubmitAttendanceForm, SubmitErrForm, SubmitForgetForm
from datetime import datetime
from django.utils import timezone
from django.urls import reverse_lazy
from django.views import generic
from .sqlite_test import KintaiCheck, labor_time
# from django.contrib.formtools.preview import FormPreview
# Create your views here.

#打刻情報を入力するページへ遷移
class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        form = SubmitAttendanceForm
        user = request.user
        object_list = SubmitAttendance.objects.filter(staff_id=user.id).order_by("id").reverse().all()
        in_out_list = ["退勤", "出勤"]
        context = {
            'form': form,
            "user": user,
            "chokkin_date": object_list[:5],
            "in_out_list":in_out_list
        }
        return render(request, 'attend/index.html', context)
index = IndexView.as_view()

#打刻エラーの原因ページへ遷移
class ErrView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        form_err = SubmitErrForm
        context = {
            'form_err': form_err,
            "user": user
        }
        return render(request, 'attend/push_err.html', context)

Err = ErrView.as_view()

#打刻忘れの時刻を記入するページへ遷移
class ForgetView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        form_forget = SubmitForgetForm
        context = {
            "hoge" : "hoge",
            'form_forget': form_forget,
            "user": user
        }
        return render(request, 'attend/result_err.html', context)

forget = ForgetView.as_view()

#打刻結果をpostする。
class ResultView(View):
    def post(self, request):
        form = SubmitAttendanceForm(request.POST)
        now = datetime.now()
        month = now.month
        day = now.day
        hour = now.hour
        minute = now.minute
        obj = form.save(commit=False)
        obj.in_out = request.POST["in_out"]
        obj.staff = request.user
        obj.date = datetime.now().date()
        obj.time = datetime.now().replace(microsecond=0).time()
        obj.save()
        kintai_bool, td_bool = KintaiCheck(obj.staff.id)
        comment_add = False
        if td_bool:
            comment = "打刻エラー: 前回の打刻から5分経過していないので、打刻が認められません。"
            #最新のレコードを削除
            SubmitAttendance.objects.filter(id=obj.id, staff_id=obj.staff.id).delete()
        elif kintai_bool:
            if request.POST["in_out"] == '1':
                comment = str(month) + "月" + str(day) +"日" + str(hour) + "時" + str(minute) + "分\n" + "出勤確認しました。今日も頑張りましょう！"
            else:
                work_time, in_time, out_time, overwork = labor_time(obj.staff.id)
                if work_time == "unknown":
                    comment = "打刻エラー: 出勤打刻をしてください。"
                    #最新のレコードを削除
                    SubmitAttendance.objects.filter(id=obj.id, staff_id=obj.staff.id).delete()
                else:
                    comment = str(month) + "月" + str(day) +"日" + str(hour) + "時" + str(minute) + "分\n" + "退勤確認しました。\n"\
                        "労働時間は" + str(work_time.seconds // 3600) + "時間"+ str((work_time.seconds % 3600) // 60) + "分です。"\
                                            + "お疲れ様でした\(^o^)/！"
                if overwork:
                    work_time = str(work_time.seconds // 3600) + ":"+ str((work_time.seconds % 3600) // 60)
                    obj_over = OverWorkTime.objects.create(
                        staff = obj.staff,
                        date_time_in = str(in_time),
                        date_time_out = str(out_time),
                        worktime = work_time
                    )
                    obj_over.save()
                    comment_add = "働きすぎです。超過労働リストに登録されました。"
        else:
            in_out_list = ["退勤", "出勤"]
            comment = "打刻エラー: " + str(in_out_list[int(obj.in_out) - 1]) + "打刻を忘れているか打刻ミスをしています。"
            form_err = SubmitErrForm
            context = {
                'form_err': form_err,
                'comment': comment
                }
            return render(request, 'attend/push_err.html', context)
        context = {
                'comment': comment,
                'comment_add': comment_add
            }
        return render(request, 'attend/result.html', context)
result = ResultView.as_view()

#打刻エラーの原因をpostする
class ResultErrView(View):
    def post(self, request):
        form_err = SubmitErrForm(request.POST)
        obj_err = form_err.save(commit=False)
        obj_err.staff = request.user
        obj_err.err_cause = request.POST["err_cause"]
        in_out_list = ["退勤", "出勤"]
        if request.POST["err_cause"] == '2':
            obj = SubmitAttendance.objects.all().filter(staff_id=obj_err.staff.id).order_by("id").reverse()[0]
            obj.in_out = str(abs(int(obj.in_out) -1))
            #最新のレコードを削除
            SubmitAttendance.objects.all().filter(staff_id=obj_err.staff.id).order_by("id").reverse()[0].delete()
            obj.save()
            select = 2
            comment = str(in_out_list[int(obj.in_out)]) + "打刻が完了しました。"
            context = {
            "select": select,
            "comment": comment
            }
        else:
            select = 1
            form_forget = SubmitForgetForm
            comment = "忘れていた打刻時間を記入して、管理者に報告してください。"
            context = {
                "select": select,
                "comment": comment,
            'form_forget': form_forget
            }
        return render(request, 'attend/result_err.html', context)
result_err = ResultErrView.as_view()

#打刻を忘れた時刻をpostする
class ResultForgetView(View):
    def post(self, request):
        form_forget = SubmitForgetForm(request.POST)
        obj_forget = form_forget.save(commit=False)
        obj_forget.staff = request.user
        obj = SubmitAttendance.objects.all().filter(staff_id=obj_forget.staff.id).order_by("id").reverse()[0]
        obj_forget.in_out = str(abs(int(obj.in_out) -1))
        obj_forget.date_time_forget = request.POST["date_time_forget"]
        obj_forget.save()
        comment = "送信されました。" + "打刻忘れを管理者に報告してください。"
        context = {
            "comment": comment
        }
        return render(request, 'attend/result_forget.html', context)
result_forget = ResultForgetView.as_view()

attend/templates/attend/base.html
{% load static %}
<html>
<head>
    <meta charset='utf-8'>
    <link rel="stylesheet" type="text/css" href="{% static 'attend/css/style.css' %}">
    <title>勤怠打刻ページ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>    
<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

attend/templates/attend/index.html
{% extends "attend/base.html" %}
{% block content %}

    {% if user.is_authenticated %}
        <div class="container">
            <form method="post" action="{% url 'attend:result' %}" onsubmit="return beforeSubmit()">
            {% csrf_token %}
                <h2 style="padding-top: 20px;">XX社勤怠管理システム</h2>
                <h3>{{  user  }} さん</h3>
                {% if user.is_superuser %}
                <p>管理者サイトは<a href="/admin">こちら</a></p>
                {% endif %}
                <h3 id="time"></h3>
                    <script>
                    time();
                    function time(){
                        var now = new Date();
                        document.getElementById("time").innerHTML = now.toLocaleString();
                    }
                    setInterval('time()',1000);
                    </script>
                <h2 style="padding: 30px;"><input type="hidden" name="in_out">
                    {{ form.in_out }}
                </h2>
                <script>
                    function beforeSubmit() {
                      if( window.confirm("選択した内容でよろしいですか？") ) {
                        return true;
                      } else {
                        return false;
                      }
                    }
                  </script>
                <p><input class="btn btn-primary" type="submit" value="送信" id="submit"></p>
            </form>
            <h4 style="padding-top: 30px;">直近の打刻</h4>
            <ul>
            {% for obj in chokkin_date %}
              {% if obj.in_out == 1 %}
                <li>{{ obj.date }}{{ obj.time }} {{ in_out_list.1 }}</li>
              {% else %}
              <li>{{ obj.date }}{{ obj.time }} {{ in_out_list.0 }}</li>
              {% endif %}
            {% endfor %}
              </ul>
            <a href="accounts/logout">&nbsp;ログアウト</a>
        </div>
    {% endif %}

{% endblock %}

attend/templates/attend/push_err.html
{% extends 'attend/base.html' %}
{% block content %}
    <div class="container">
        <form method="post" action="{% url 'attend:result_err' %}">
            {% csrf_token %}
            <h3 style="padding-top: 20px; padding-bottom: 20px;"">打刻エラーです。</h3>
            <div class="container"><h4>原因1. 打刻忘れ</h4>
            <ul>出勤/退勤打刻を忘れていた。</ul>
            <h4>原因2. 打刻ミス</h4>
            <ul>出勤(退勤)打刻をしなければならないのに退勤(出勤)打刻をしてしまった。</ul>
            <h3 style="color:blue">打刻エラーの原因はどちらですか？</h3>
            </div>
            <h2 style="padding:30px"><input type="hidden" name="err_cause">
                {{ form_err.err_cause }}
            </h2>
            <p><input class="btn btn-primary" type="submit" value="送信" id="submit"></p>
        </form>
    </div>
{% endblock %}

attend/templates/attend/result.html
{% extends 'attend/base.html' %}
{% block content %}
<div class="container">
    <h3 style="padding: 10px;">{{ comment }}</h3>
    {% if comment_add %}
    <h3 style="color:red; padding-left: 10px;">{{ comment_add }}</h3>
    {% endif %}
    <br>
    <p><a href="/">戻る</a></p>
    <p><a href="../accounts/logout/">ログアウト</a></p>
</div>
{% endblock  %}

attend/templates/attend/result_err.html
{% extends 'attend/base.html' %}

{% block content %}
{% if select == 2 %}
<div class="container">
    <h3 style="padding: 20px;"">{{ comment }}</h3>
    <p><a href="/">戻る</a></p>
    <p><a href="../accounts/logout/">ログアウト</a></p>
    </div>
{% else %}
    <h3 style="padding: 20px;">{{ comment }}</h3>
    <div class="container">
        <form method="post" action="{% url 'attend:result_forget' %}">
            {% csrf_token %}
        <h2><input type="hidden" name="date_time_forget">
            {{ form_forget.date_time_forget }}
        </h2>
        <p><input class="btn btn-primary" type="submit" value="送信" id="submit"></p>
    </form>
</div>
{% endif %}
{% endblock %}

attend/templates/attend/result_forget.html
{% extends 'attend/base.html' %}
{% block content %}
<div class="container">
<h3 style="padding:20px;">{{ comment }}</h3>
<p><a href="/">戻る</a></p>
<p><a href="../accounts/logout/">ログアウト</a></p>
</div>
{% endblock %}